# Generated by Django 4.0.6 on 2022-08-03 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[0-9]{10}')]),
        ),
    ]
