# Generated by Django 4.0.6 on 2022-08-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_comments_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commented_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
