# Generated by Django 4.0.6 on 2022-08-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0010_comments_commented_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_posts',
            field=models.ManyToManyField(null=True, to='blogapp.blogs'),
        ),
    ]
