# Generated by Django 4.0.6 on 2022-08-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_alter_userprofile_saved_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, to='blogapp.blogs'),
        ),
    ]
