# Generated by Django 4.0.6 on 2022-08-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_alter_userprofile_saved_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='joined_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
