# Generated by Django 4.0.6 on 2022-08-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_alter_userprofile_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='joined_date',
        ),
    ]
